name: biophysics-DNN
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy>=1.26.0
  - pandas>=2.2.0
  - matplotlib>=3.9.0
  - seaborn>=0.13.0
  - keras-tuner>=1.4.0
  - lime>=0.2.0
  - shap>=0.47.0
  - mdanalysis>=2.7.0
  - scikit-learn>=1.6.0
  - scipy>=1.13.0
  - h5py>=3.10.0
  - tqdm>=4.66.0
  - jupyter>=1.0.0
  - notebook>=7.0.0
  - ipykernel>=6.29.0
  - ipython>=8.15.0
  - jupyter_client>=8.6.0
  - jupyter_core>=5.7.0
  - nbformat>=5.10.0
  - nbconvert>=7.16.0
  - pip:
    - tensorflow==2.16.2  # Use the exact version from PyPI
    - keras==3.0.0
    - keras-tuner==1.4.7
    - kt-legacy>=1.0.5